begin;

create extension if not exists pgcrypto;

create table if not exists public.country_catalog (
  code text primary key check (code = upper(code)),
  name text not null,
  iso2 text,
  iso3 text,
  numeric_code text,
  geographic_region text not null,
  subregion text not null default '',
  tier smallint not null check (tier between 1 and 3),
  is_core boolean not null default false,
  groups text[] not null default '{}',
  entity_type text not null default 'country',
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  metadata jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.countries (
  code text primary key references public.country_catalog(code) on update cascade,
  name text not null,
  region text not null,
  lat double precision not null check (lat between -90 and 90),
  lon double precision not null check (lon between -180 and 180),
  gdp_weight double precision,
  tier smallint not null check (tier between 1 and 3),
  coverage_score numeric(5,1) not null default 0 check (coverage_score between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indicators (
  id text primary key,
  name text not null,
  category text not null,
  unit text not null,
  frequency text not null,
  transformation text,
  description text,
  methodology_version text not null default 'v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.observations (
  id bigint generated by default as identity primary key,
  country_code text not null references public.countries(code) on update cascade,
  indicator_id text not null references public.indicators(id) on update cascade,
  period text not null,
  observation_date date not null,
  value double precision not null check (
    value > '-Infinity'::double precision and value < 'Infinity'::double precision
    and value <> 'NaN'::double precision
  ),
  source text not null,
  source_series_id text,
  retrieved_at timestamptz not null,
  vintage_at timestamptz not null,
  source_vintage_date date,
  validation_status text not null default 'VALID'
    check (validation_status in ('VALID', 'WARNING', 'FAILED')),
  validation_warnings text[] not null default '{}',
  source_metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  unique (country_code, indicator_id, period, vintage_at)
);

create index if not exists observations_series_period_idx
  on public.observations(country_code, indicator_id, period, vintage_at desc);
create index if not exists observations_retrieved_idx
  on public.observations(retrieved_at desc);

create table if not exists public.derived_metrics (
  id bigint generated by default as identity primary key,
  country_code text not null references public.countries(code) on update cascade,
  metric_id text not null,
  period text not null,
  value double precision,
  value_text text,
  methodology_version text not null,
  input_observation_ids bigint[] not null default '{}',
  input_fingerprint text not null,
  validation_status text not null default 'VALID'
    check (validation_status in ('VALID', 'WARNING', 'FAILED')),
  computed_at timestamptz not null default now(),
  unique (country_code, metric_id, period, methodology_version, input_fingerprint)
);

create table if not exists public.data_lineage (
  id bigint generated by default as identity primary key,
  observation_id bigint references public.observations(id),
  derived_metric_id bigint references public.derived_metrics(id),
  provider text not null,
  provider_url text,
  source_payload jsonb,
  transformation text,
  recorded_at timestamptz not null default now(),
  check (num_nonnulls(observation_id, derived_metric_id) = 1)
);

create table if not exists public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  source text not null,
  status text not null check (status in ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'NOOP')),
  checked_series integer not null default 0,
  inserted_rows integer not null default 0,
  skipped_rows integer not null default 0,
  failed_series integer not null default 0,
  message text,
  details jsonb not null default '{}'
);

create or replace view public.current_observations with (security_invoker = true) as
select distinct on (country_code, indicator_id, period) *
from public.observations
order by country_code, indicator_id, period, vintage_at desc, id desc;

alter table public.country_catalog enable row level security;
alter table public.countries enable row level security;
alter table public.indicators enable row level security;
alter table public.observations enable row level security;
alter table public.derived_metrics enable row level security;
alter table public.data_lineage enable row level security;
alter table public.sync_runs enable row level security;

revoke all on public.country_catalog, public.countries, public.indicators,
  public.observations, public.derived_metrics, public.data_lineage,
  public.sync_runs, public.current_observations from anon, authenticated;

comment on table public.observations is 'Immutable release vintages. Revisions insert a new vintage instead of overwriting history.';
comment on table public.derived_metrics is 'Deterministic outputs only; no forecasts or causal estimates.';
comment on column public.countries.coverage_score is 'Availability of valid required indicators, not economic strength.';

commit;
